# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(362, 582)
        MainWindow.setMinimumSize(QtCore.QSize(362, 582))
        MainWindow.setMaximumSize(QtCore.QSize(362, 582))
        font = QtGui.QFont()
        font.setPointSize(7)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(20, 20, 20, 1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(300, 300))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Login_image.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"color: rgb(134, 134, 134);\n"
"\n"
"\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.lineEdit_username = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(238, 238, 236);\n"
"    border-radius: 10px;\n"
"    padding: 2px;\n"
"    background-color: #fff;\n"
"   /* color: rgb(200, 200, 200); */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1px solid rgb(186, 189, 182);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid   rgb(114, 159, 207);\n"
"    color: rgb(100, 100, 100);\n"
"}")
        self.lineEdit_username.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.verticalLayout.addWidget(self.lineEdit_username)
        self.lineEdit_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("QLineEdit {\n"
"    border: 1px solid rgb(238, 238, 236);\n"
"    border-radius: 10px;\n"
"    padding: 2px;\n"
"    background-color: #fff;\n"
"   /* color: rgb(200, 200, 200); */\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 1px solid rgb(186, 189, 182);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid   rgb(114, 159, 207);\n"
"    color: rgb(100, 100, 100);\n"
"}")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.verticalLayout.addWidget(self.lineEdit_password)
        self.checkBox_show_password = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_show_password.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_show_password.setFont(font)
        self.checkBox_show_password.setObjectName("checkBox_show_password")
        self.verticalLayout.addWidget(self.checkBox_show_password)
        self.button_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_login.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.button_login.setFont(font)
        self.button_login.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color:#2ecc71;\n"
"    color:#fff;\n"
"    font-size:15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border:1px solid;\n"
"    border-color: #27ae60;\n"
"    background-color: rgb(50, 227, 124);\n"
"}\n"
"\n"
" QPushButton:pressed {\n"
"    background-color: #27ae60;\n"
"    border-radius: 10px;\n"
"    border:1px solid rgb(0, 223, 108);\n"
"}\n"
"")
        self.button_login.setObjectName("button_login")
        self.verticalLayout.addWidget(self.button_login)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        self.statusBar.setFont(font)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.button_login, self.lineEdit_username)
        MainWindow.setTabOrder(self.lineEdit_username, self.lineEdit_password)
        MainWindow.setTabOrder(self.lineEdit_password, self.checkBox_show_password)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label_2.setText(_translate("MainWindow", "Member Login"))
        self.lineEdit_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.checkBox_show_password.setText(_translate("MainWindow", "Show password"))
        self.button_login.setText(_translate("MainWindow", "Log in"))
